config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :requests
  resources :requests
  resources :requests
  resources :requests

  root 'requests#index'

  resources :requests

end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id             :integer          not null, primary key
#  firstname      :string           not null
#  lastname       :string           not null
#  days           :integer          not null
#  out_of_country :boolean
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Request < ActiveRecord::Base
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :days, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :out_of_country, :inclusion => {:in => [true, false]}, if: -> { days and days > 5 }

  before_validation :check_days

  def check_days
    self.out_of_country = nil unless days and days > 5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit :firstname, :lastname, :days, :out_of_country
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Vacation
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/requests/_form.html.slim
= form_for(@request) do |f|
  - if @request.errors.any?
    #error_explanation
      h2
        = pluralize(@request.errors.count, "error")
        |  prohibited this request from being saved:
      ul
        - @request.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :firstname
    br
    = f.text_field :firstname
  .field
    = f.label :lastname
    br
    = f.text_field :lastname
  .field
    = f.label :days
    br
    = f.number_field :days, min: 0, id: :request_days
  .field[id="out_of_country_container"]
    = f.label :out_of_country
    br
    = f.check_box :out_of_country
  .actions
    = f.submit

app/views/requests/edit.html.slim
h1
  | Editing Request
= render 'form'
= link_to 'Show', @request
|  | 
= link_to 'Back', requests_path

app/views/requests/index.html.slim
p#notice
  = notice
h1
  | Listing Requests
table
  thead
    tr
      th
        | Firstname
      th
        | Lastname
      th
        | Days
      th
        | Out of country
      th[colspan="3"]
  tbody
    - @requests.each do |request|
      tr
        td
          = request.firstname
        td
          = request.lastname
        td
          = request.days
        td
          = request.out_of_country
        td
          = link_to 'Show', request
        td
          = link_to 'Edit', edit_request_path(request)
        td
          = link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Request', new_request_path

app/views/requests/new.html.slim
h1
  | New Request
= render 'form'
= link_to 'Back', requests_path

app/views/requests/show.html.slim
p#notice
  = notice
p
  strong
    | Firstname:
  = @request.firstname
p
  strong
    | Lastname:
  = @request.lastname
p
  strong
    | Days:
  = @request.days
p
  strong
    | Out of country:
  = @request.out_of_country
= link_to 'Edit', edit_request_path(@request)
|  | 
= link_to 'Back', requests_path